version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'csstype'
        versions:
          - '3.1.3'
    groups:
      typescript:
        patterns:
          - 'typescript'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      non-major:
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - 'typescript'

      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'
          - 'eslint-plugin-storybook'
