packages:
  - 'packages/*'

strictPeerDependencies: false
autoInstallPeers: true
enablePrePostScripts: true

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

overrides:
  react: 19.2.7
  react-dom: 19.2.7
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  js-yaml@<=4.1.1: ^4.1.2

minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - js-yaml@4.1.2
