export {
  ScreenSize,
  type ScreenSizeLiteral,
  getLiteralScreenSize,
  type BreakpointBasedProps,
  type Placement,
  type BaseComponentProps,
  type BaseComponentPropsWithChildren,
  getBaseHTMLProps,
  isKeyboardEvent,
  useCombinedRef,
  useFloatPosition,
  useFocusTrap,
  useMountTransition,
  useOnClickOutside,
  useOnKeyDown,
  useReturnFocusOnBlur,
  useRoveFocus,
  useScreenSize,
} from '@norges-domstoler/dds-core';
