
// Do not edit directly, this file was auto-generated.

export const ddsFontFamilySans = "'IBM Plex Sans', Arial, sans-serif";
export const ddsFontFamilyMonospace = "'IBM Plex Mono', 'Courier New', monospace"; // For kode
export const ddsFontSizeX5 = "5rem";
export const ddsFontSizeX5NumberRem = 5;
export const ddsFontSizeX4 = "4rem";
export const ddsFontSizeX4NumberRem = 4;
export const ddsFontSizeX3 = "3rem";
export const ddsFontSizeX3NumberRem = 3;
export const ddsFontSizeX25 = "2.5rem";
export const ddsFontSizeX25NumberRem = 2.5;
export const ddsFontSizeX2 = "2rem";
export const ddsFontSizeX2NumberRem = 2;
export const ddsFontSizeX15 = "1.5rem";
export const ddsFontSizeX15NumberRem = 1.5;
export const ddsFontSizeX125 = "1.25rem";
export const ddsFontSizeX125NumberRem = 1.25;
export const ddsFontSizeX1125 = "1.125rem";
export const ddsFontSizeX1125NumberRem = 1.125;
export const ddsFontSizeX1 = "1rem";
export const ddsFontSizeX1NumberRem = 1;
export const ddsFontSizeX0875 = "0.875rem";
export const ddsFontSizeX0875NumberRem = 0.875;
export const ddsFontSizeX075 = "0.75rem";
export const ddsFontSizeX075NumberRem = 0.75;
export const ddsFontWeightLight = "300";
export const ddsFontWeightNormal = "400";
export const ddsFontWeightSemiBold = "500";
export const ddsFontWeightBold = "600";
export const ddsFontLineheightX1 = 1.5; // Brukes på str ×1_25 og mindre 
export const ddsFontLineheightX2 = 1.35; // Brukes på str x1.5, ×2 og ×3 
export const ddsFontLineheightX3 = 1.2; // Brukes på str ×3 og større
export const ddsFontLineheightList = 2; // Brukes på lister
export const ddsFontLetterSpacingTight = "-0.01em"; // Brukes på str ×2.5 og større
export const ddsFontLetterSpacingNormal = "0em"; // Brukes på str ×1 og opp til og med ×2
export const ddsFontLetterSpacingLoose = "0.01em"; // Brukes på størrelser under ×1
export const ddsFontParagraphSpacingSmall = "1em";
export const ddsFontParagraphSpacingSmallNumberEm = 1; // Brukes på str ×1_25 og mindre 
export const ddsFontParagraphSpacingMedium = "0.66em";
export const ddsFontParagraphSpacingMediumNumberEm = 0.66; // Brukes på str x1.5, ×2 og ×3 
export const ddsFontParagraphSpacingLarge = "0.5em";
export const ddsFontParagraphSpacingLargeNumberEm = 0.5; // Brukes på str ×3 og større
export const ddsFontParagraphSpacingHeading = "0.4em";
export const ddsFontParagraphSpacingHeadingNumberEm = 0.4; // Brukes på på alle headere (bottom)
export const ddsFontStyleUnderline = "underline";
export const ddsFontStyleNormal = "none";
export const ddsFontStyleItalic = "italic";
export const ddsSpacingPaddingTopHeading = "0.7em";
export const ddsSpacingPaddingTopHeadingNumberEm = 0.7; // Ekstra spacing over dds-header. 70% av størrelsen på headeren
export const ddsSpacingX0 = "0rem";
export const ddsSpacingX0NumberRem = 0;
export const ddsSpacingX0125 = "0.125rem";
export const ddsSpacingX0125NumberRem = 0.125;
export const ddsSpacingX025 = "0.25rem";
export const ddsSpacingX025NumberRem = 0.25;
export const ddsSpacingX05 = "0.5rem";
export const ddsSpacingX05NumberRem = 0.5;
export const ddsSpacingX075 = "0.75rem";
export const ddsSpacingX075NumberRem = 0.75;
export const ddsSpacingX1 = "1rem";
export const ddsSpacingX1NumberRem = 1;
export const ddsSpacingX15 = "1.5rem";
export const ddsSpacingX15NumberRem = 1.5;
export const ddsSpacingX2 = "2rem";
export const ddsSpacingX2NumberRem = 2;
export const ddsSpacingX25 = "2.5rem";
export const ddsSpacingX25NumberRem = 2.5;
export const ddsSpacingX3 = "3rem";
export const ddsSpacingX3NumberRem = 3;
export const ddsSpacingX4 = "4rem";
export const ddsSpacingX4NumberRem = 4;
export const ddsSpacingX6 = "6rem";
export const ddsSpacingX6NumberRem = 6;
export const ddsSpacingX10 = "10rem";
export const ddsSpacingX10NumberRem = 10;
export const ddsShadow1 = "1px 2px 4px 0px rgba(11, 13, 14, 10%)";
export const ddsShadow2 = "2px 4px 8px 0px rgba(11, 13, 14, 10%)";
export const ddsShadow3 = "4px 8px 16px 0px rgba(11, 13, 14, 10%)";
export const ddsShadow4 = "8px 16px 32px 0px rgba(11, 13, 14, 10%)";
export const ddsGridXsGutterSize = "16px";
export const ddsGridXsGutterSizeNumberPx = 16;
export const ddsGridXsCount = "4";
export const ddsGridSmGutterSize = "16px";
export const ddsGridSmGutterSizeNumberPx = 16;
export const ddsGridSmCount = "8";
export const ddsGridLgGutterSize = "24px";
export const ddsGridLgGutterSizeNumberPx = 24;
export const ddsGridLgCount = "12";
export const ddsGridMdGutterSize = "24px";
export const ddsGridMdGutterSizeNumberPx = 24;
export const ddsGridMdCount = "12";
export const ddsGridXlGutterSize = "24px";
export const ddsGridXlGutterSizeNumberPx = 24;
export const ddsGridXlCount = "12";
export const ddsIconSizeLarge = "40px";
export const ddsIconSizeLargeNumberPx = 40;
export const ddsIconSizeMedium = "24px";
export const ddsIconSizeMediumNumberPx = 24;
export const ddsIconSizeSmall = "16px";
export const ddsIconSizeSmallNumberPx = 16;
export const ddsBreakpointXs = "1px";
export const ddsBreakpointXsNumberPx = 1;
export const ddsBreakpointSm = "600px";
export const ddsBreakpointSmNumberPx = 600;
export const ddsBreakpointMd = "960px";
export const ddsBreakpointMdNumberPx = 960;
export const ddsBreakpointLg = "1280px";
export const ddsBreakpointLgNumberPx = 1280;
export const ddsBreakpointXl = "1920px";
export const ddsBreakpointXlNumberPx = 1920;
export const ddsZindexSkiptocontent = "250"; // Brukes for dds-skiptocontent
export const ddsZindexModalBackdrop = "200"; // Brukes for dds-modal
export const ddsZindexDrawer = "180"; // Brukes for dds-drawer
export const ddsZindexDrawerBackdrop = "180"; // Brukes for dds-drawer
export const ddsZindexOverflowmenu = "160"; // Brukes for dds-overflowmenu
export const ddsZindexPopover = "140"; // Brukes for dds-popover og kalender i datepicker
export const ddsZindexTooltip = "120"; // Brukes for dds-tooltip
export const ddsZindexDropdown = "100"; // Dropdown brukes for bl.a søkeforslag, dropdown i select
export const ddsZindexSticky = "50"; // Sticky header skal dekke til flat innhold i gruppen (tabell o.l.). Den skal legge seg under elementer som stiller med egne flater
export const ddsZindexAbsoluteElement = "1"; // Dekorative elementer med absolutt posisjon, som ellers hadde blitt skjult bak forelder
export const ddsColorDataRed100 = "#f8d2d4";
export const ddsColorDataRed200 = "#f0a5a9";
export const ddsColorDataRed300 = "#e9787e";
export const ddsColorDataRed400 = "#e14b53";
export const ddsColorDataRed500 = "#da1e28";
export const ddsColorDataRed600 = "#ae1820";
export const ddsColorDataRed700 = "#831218";
export const ddsColorDataRed800 = "#570c10";
export const ddsColorDataRed900 = "#2c0608";
export const ddsColorDataMagenta100 = "#eed3df";
export const ddsColorDataMagenta200 = "#dfa5bf";
export const ddsColorDataMagenta300 = "#cf789e";
export const ddsColorDataMagenta400 = "#c74f84";
export const ddsColorDataMagenta500 = "#b62665";
export const ddsColorDataMagenta600 = "#8a1a4b";
export const ddsColorDataMagenta700 = "#671438";
export const ddsColorDataMagenta800 = "#440e26";
export const ddsColorDataMagenta900 = "#220713";
export const ddsColorDataBrown100 = "#f0ddd5";
export const ddsColorDataBrown200 = "#e1bcac";
export const ddsColorDataBrown300 = "#d19a82";
export const ddsColorDataBrown400 = "#c27959";
export const ddsColorDataBrown500 = "#b3572f";
export const ddsColorDataBrown600 = "#8f4626";
export const ddsColorDataBrown700 = "#6b341c";
export const ddsColorDataBrown800 = "#482313";
export const ddsColorDataBrown900 = "#241109";
export const ddsColorDataOlive100 = "#e6e4d0";
export const ddsColorDataOlive200 = "#cdc9a1";
export const ddsColorDataOlive300 = "#b3ae71";
export const ddsColorDataOlive400 = "#989344";
export const ddsColorDataOlive500 = "#7c7518";
export const ddsColorDataOlive600 = "#635e13";
export const ddsColorDataOlive700 = "#4a460e";
export const ddsColorDataOlive800 = "#322f0a";
export const ddsColorDataOlive900 = "#191705";
export const ddsColorDataGreen100 = "#d1e6d7";
export const ddsColorDataGreen200 = "#a3ccaf";
export const ddsColorDataGreen300 = "#75b388";
export const ddsColorDataGreen400 = "#479960";
export const ddsColorDataGreen500 = "#198038";
export const ddsColorDataGreen600 = "#14662d";
export const ddsColorDataGreen700 = "#0f4d22";
export const ddsColorDataGreen800 = "#0a3316";
export const ddsColorDataGreen900 = "#051a0b";
export const ddsColorDataTeal100 = "#c2e2e1";
export const ddsColorDataTeal200 = "#90ccc9";
export const ddsColorDataTeal300 = "#5dafad";
export const ddsColorDataTeal400 = "#2c9390";
export const ddsColorDataTeal500 = "#007d79";
export const ddsColorDataTeal600 = "#006461";
export const ddsColorDataTeal700 = "#004b49";
export const ddsColorDataTeal800 = "#003230";
export const ddsColorDataTeal900 = "#001918";
export const ddsColorDataDeepblue100 = "#b9d7e5";
export const ddsColorDataDeepblue200 = "#96c5d9";
export const ddsColorDataDeepblue300 = "#6aa8c3";
export const ddsColorDataDeepblue400 = "#3e8bac";
export const ddsColorDataDeepblue500 = "#196b8f";
export const ddsColorDataDeepblue600 = "#135774";
export const ddsColorDataDeepblue700 = "#0e455e";
export const ddsColorDataDeepblue800 = "#0d3445";
export const ddsColorDataDeepblue900 = "#05151d";
export const ddsColorDataBlue100 = "#cfe0ff";
export const ddsColorDataBlue200 = "#9fc0ff";
export const ddsColorDataBlue300 = "#6fa1fe";
export const ddsColorDataBlue400 = "#3f81fe";
export const ddsColorDataBlue500 = "#0f62fe";
export const ddsColorDataBlue600 = "#0c4ecb";
export const ddsColorDataBlue700 = "#093b98";
export const ddsColorDataBlue800 = "#062766";
export const ddsColorDataBlue900 = "#031433";
export const ddsColorDataPurple100 = "#e8d9fe";
export const ddsColorDataPurple200 = "#d0b2fe";
export const ddsColorDataPurple300 = "#b98cfd";
export const ddsColorDataPurple400 = "#a165fd";
export const ddsColorDataPurple500 = "#8a3ffc";
export const ddsColorDataPurple600 = "#6e32ca";
export const ddsColorDataPurple700 = "#532697";
export const ddsColorDataPurple800 = "#371965";
export const ddsColorDataPurple900 = "#1c0d32";
export const ddsColorDataGray100 = "#e3e3e3";
export const ddsColorDataGray200 = "#c7c7c7";
export const ddsColorDataGray300 = "#aaaaaa";
export const ddsColorDataGray400 = "#8e8e8e";
export const ddsColorDataGray500 = "#727272";
export const ddsColorDataGray600 = "#5b5b5b";
export const ddsColorDataGray700 = "#444444";
export const ddsColorDataGray800 = "#2e2e2e";
export const ddsColorDataGray900 = "#171717";
export const ddsColorBgDefault = "#ffffff"; // UI shell base color
export const ddsColorBgSubtle = "#f1f3f4"; // Alternative UI shell base color
export const ddsColorSurfaceDefault = "#ffffff"; // Default bg
export const ddsColorSurfaceSubtle = "#f1f3f4"; // Subtle surface color
export const ddsColorSurfaceMedium = "#e4e6e8"; // Medium surface color
export const ddsColorSurfaceHoverDefault = "#e7f1f7"; // Hover on surface (default, subtle, medium)
export const ddsColorSurfaceHoverSubtle = "#f1f3f4"; // Subtle hover on surface (default, medium)
export const ddsColorSurfaceSelectedDefault = "#e7f1f7"; // Selected state for surface (default, subtle, medium)
export const ddsColorSurfaceInverseDefault = "#354754"; // Can be used as a surface for menu, navigation, footer etc
export const ddsColorSurfaceInverseHover = "#2a3943"; // Hover on surface.inverse
export const ddsColorSurfaceInverseSelected = "#202b32"; // selected on surface.inverse
export const ddsColorSurfaceActionResting = "#106ead"; // Primary button bg
export const ddsColorSurfaceActionHover = "#0d588a"; // Hover on surface.action/selected
export const ddsColorSurfaceActionSelected = "#106ead"; // Selected state for components such as togglebutton, togglebar, progress tracker, checkbox etc
export const ddsColorSurfaceActionDangerResting = "#d83737"; // Danger button
export const ddsColorSurfaceActionDangerHover = "#ad2c2c"; // Hover on surface.action-danger
export const ddsColorSurfaceActionSelectedDisabled = "#77838c"; // bg on a selected disabled checkbox, radio etc
export const ddsColorSurfaceDangerDefault = "#fbebeb"; // tag, message, errormessage
export const ddsColorSurfaceDangerStrong = "#e47373"; // tag strong value
export const ddsColorSurfaceSuccessDefault = "#f0f9f0"; // tag, message
export const ddsColorSurfaceSuccessStrong = "#93d294"; // tag with strong value
export const ddsColorSurfaceWarningDefault = "#fefced"; // tag, message
export const ddsColorSurfaceWarningStrong = "#f7e982"; // tag strong value
export const ddsColorSurfaceInfoDefault = "#f1f8fd"; // tag, message
export const ddsColorSurfaceInfoStrong = "#9eceee"; // tag strong value
export const ddsColorSurfacePaperDefault = "#ffffff"; // modal, drawer, popover etc
export const ddsColorSurfaceBackdropDefault = "#0b0d0e80"; // background overlay for modals (50%)
export const ddsColorSurfaceFieldDefault = "#ffffff"; // Form elements (textinput, datepicker etc)
export const ddsColorSurfaceFieldDisabled = "#f1f3f4"; // disabled state on surface.field
export const ddsColorSurfaceHighlightedDefault = "#fce5dd"; // bg for highlighted text on text.default. Use with $Text
export const ddsColorSurfaceScrollbar = "#adb5ba"; // Used for scrollbar
export const ddsColorSurfaceNotification = "#d83737"; // bg on a notification
export const ddsColorSurfaceSkeleton = "#d6dadd"; // Used for skeleton
export const ddsColorBorderDefault = "#77838c"; // Form components, togglebutton, secondary button, checkbox etc
export const ddsColorBorderSubtle = "#d6dadd"; // Dropdown, tooltip, overflow etc
export const ddsColorBorderInverse = "#acbbc6"; // Border or divider on surface.inverse
export const ddsColorBorderActionDefault = "#106ead"; // Used in progress tracker
export const ddsColorBorderActionHover = "#0d588a"; // Hover on secondary button etc
export const ddsColorBorderSuccess = "#65be66"; // Used with tag-default
export const ddsColorBorderWarning = "#f4e04d"; // Tag.default
export const ddsColorBorderDanger = "#d83737"; // Tag.default, error message field
export const ddsColorBorderInfo = "#75b9e6"; // Tag.default
export const ddsColorBorderOnAction = "#ffffff"; // Used on primary split button
export const ddsColorTextDefault = "#0b0d0e"; // default text, heading, body. on surface.hover
export const ddsColorTextMedium = "#3a4146"; // Label, etc
export const ddsColorTextSubtle = "#545c62"; // Disabled or less important text
export const ddsColorTextOnInverse = "#ffffff"; // On surface.inverse
export const ddsColorTextOnAction = "#ffffff"; // On surface.action (primary and danger button)
export const ddsColorTextOnStatusDefault = "#0b0d0e"; // On default status surfaces
export const ddsColorTextOnStatusStrong = "#0b0d0e"; // On status surfaces with strong prop
export const ddsColorTextActionResting = "#106ead"; // Link, number in progress tracker
export const ddsColorTextActionHover = "#0d588a"; // Hover on text.action
export const ddsColorTextRequiredfield = "#d83737"; // Asterix to indicate required field
export const ddsColorTextActionVisited = "#7f29b4"; // Used for visited links
export const ddsColorTextActionVisitedOnInverse = "#cca9e1"; // Used for visited links on inverse surfaces
export const ddsColorTextOnNotification = "#ffffff"; // Used on surface.notification
export const ddsColorTextDanger = "#ad2c2c"; // Error text on paper, or default or subtle surafce/bg
export const ddsColorIconDefault = "#0b0d0e"; // Often used with text.default
export const ddsColorIconMedium = "#3a4146"; // Often used with text.medium
export const ddsColorIconSubtle = "#545c62"; // Often used with text.subtle
export const ddsColorIconOnInverse = "#ffffff"; // On surface.inverse
export const ddsColorIconOnAction = "#ffffff"; // On surface.action (primary and danger button)
export const ddsColorIconActionResting = "#106ead"; // Often used with Text.action
export const ddsColorIconActionHover = "#0d588a"; // hover on icon-action
export const ddsColorIconOnSuccessDefault = "#3d723d"; // On surface.success-default
export const ddsColorIconOnSuccessStrong = "#0b0d0e"; // On surface-success-strong
export const ddsColorIconOnWarningDefault = "#9a8c26"; // On surface.warning-default
export const ddsColorIconOnWarningStrong = "#0b0d0e"; // On surface.warning-strong
export const ddsColorIconOnDangerDefault = "#ad2c2c"; // On surface.danger-default
export const ddsColorIconOnDangerStrong = "#0b0d0e"; // On surface.danger-strong
export const ddsColorIconOnInfoDefault = "#3e7192"; // On surface.info-default
export const ddsColorIconOnInfoStrong = "#0b0d0e"; // On surface.info-strong
export const ddsColorIconDanger = "#ad2c2c"; // Error icon on paper, or default or subtle surafce/bg
export const ddsColorBrandPrimaryDefault = "#354754"; // Primary brand color
export const ddsColorBrandPrimarySubtle = "#eaeff4"; // Primary brand color
export const ddsColorBrandPrimaryMedium = "#4f6a7e"; // Primary brand color
export const ddsColorBrandPrimaryStrong = "#202b32"; // Primary brand color
export const ddsColorBrandSecondaryDefault = "#9ab8b7"; // Secondary brand color
export const ddsColorBrandSecondarySubtle = "#e6eded"; // Secondary brand color
export const ddsColorBrandSecondaryMedium = "#b8cdcd"; // Secondary brand color
export const ddsColorBrandSecondaryStrong = "#4d6463"; // Secondary brand color
export const ddsColorBrandTertiaryDefault = "#f27e55"; // Tertiary brand color
export const ddsColorBrandTertiarySubtle = "#fce5dd"; // Tertiary brand color
export const ddsColorBrandTertiaryMedium = "#f2a68f"; // Tertiary brand color
export const ddsColorBrandTertiaryStrong = "#d45d32"; // Tertiary brand color
export const ddsColorFocusOutside = "#2a4b61"; // Contrast to .inside
export const ddsColorFocusInside = "#f1f8fd"; // Contrast to .outside
export const ddsColorData10Default = "#196b8f";
export const ddsColorData10Subtle = "#96c5d9";
export const ddsColorData10Border = "#196b8f";
export const ddsColorData01Default = "#0f62fe";
export const ddsColorData01Subtle = "#9fc0ff";
export const ddsColorData01Border = "#0f62fe";
export const ddsColorData02Default = "#b3572f";
export const ddsColorData02Subtle = "#e1bcac";
export const ddsColorData02Border = "#b3572f";
export const ddsColorData03Default = "#727272";
export const ddsColorData03Subtle = "#c7c7c7";
export const ddsColorData03Border = "#727272";
export const ddsColorData04Default = "#198038";
export const ddsColorData04Subtle = "#a3ccaf";
export const ddsColorData04Border = "#198038";
export const ddsColorData05Default = "#8a3ffc";
export const ddsColorData05Subtle = "#d0b2fe";
export const ddsColorData05Border = "#8a3ffc";
export const ddsColorData06Default = "#b62665";
export const ddsColorData06Subtle = "#dfa5bf";
export const ddsColorData06Border = "#b62665";
export const ddsColorData07Default = "#7c7518";
export const ddsColorData07Subtle = "#cdc9a1";
export const ddsColorData07Border = "#7c7518";
export const ddsColorData08Default = "#da1e28";
export const ddsColorData08Subtle = "#f0a5a9";
export const ddsColorData08Border = "#da1e28";
export const ddsColorData09Default = "#007d79";
export const ddsColorData09Subtle = "#90ccc9";
export const ddsColorData09Border = "#007d79";
export const ddsFontLabelMedium = "600 0.875rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Label for form components
export const ddsFontBodyXsmall = "400 0.75rem/1.5 'IBM Plex Sans', Arial, sans-serif"; //  used with xsmall button and input fields
export const ddsFontBodySmall = "400 0.875rem/1.5 'IBM Plex Sans', Arial, sans-serif"; //  used with small button and input fields
export const ddsFontBodyMedium = "400 1rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // standard body text, used with medium button and input fields
export const ddsFontBodyLarge = "400 1.125rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Used for large button and large search
export const ddsFontHeadingXxsmall = "600 0.75rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Default h6
export const ddsFontHeadingXsmall = "600 0.875rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Default h5
export const ddsFontHeadingSmall = "600 1rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Default h4
export const ddsFontHeadingMedium = "600 1.125rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Default h3
export const ddsFontHeadingLarge = "400 clamp(1.25rem, 0.833rem + 1.111vw, 1.5rem)/1.35 'IBM Plex Sans', Arial, sans-serif"; // Default h2
export const ddsFontHeadingXlarge = "400 clamp(1.5rem, 0.667rem + 2.222vw, 2rem)/1.35 'IBM Plex Sans', Arial, sans-serif"; // Default H1
export const ddsFontHeadingXxlarge = "300 clamp(2.5rem, 1.667rem + 2.222vw, 3rem)/1.2 'IBM Plex Sans', Arial, sans-serif"; // Display or extra large page title (h1)
export const ddsFontLeadMedium = "300 1.125rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Lead brukes som ingress når man skriver artikler etc
export const ddsFontCodeMedium = "400 1rem/1.5 'IBM Plex Mono', 'Courier New', monospace"; // Brukes for kodesnutter etc
export const ddsBorderRadiusButton = "2px";
export const ddsBorderRadiusButtonNumberPx = 2; // For use in button component and togglebutton
export const ddsBorderRadiusSurface = "4px";
export const ddsBorderRadiusSurfaceNumberPx = 4; // Most surfaces, for example cards, papers, messages, backgrounds in GUI
export const ddsBorderRadiusInput = "2px";
export const ddsBorderRadiusInputNumberPx = 2; // All input fields, and check boxes
export const ddsBorderRadiusChip = "4px";
export const ddsBorderRadiusChipNumberPx = 4; // Chips and tags
export const ddsBorderRadiusRounded = "9999px";
export const ddsBorderRadiusRoundedNumberPx = 9999; // Rounded and circular components such as radiobutton, toggle, togglebutton and progress tracker
export const ddsFontHeadingXxlargeLetterSpacing = "-0.01em";
export const ddsFontHeadingXxlargeParagraphSpacing = "0.4em";
export const ddsFontHeadingXxlargeParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingXlargeLetterSpacing = "0em";
export const ddsFontHeadingXlargeParagraphSpacing = "0.4em";
export const ddsFontHeadingXlargeParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingLargeLetterSpacing = "0em";
export const ddsFontHeadingLargeParagraphSpacing = "0.4em";
export const ddsFontHeadingLargeParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingMediumLetterSpacing = "0em";
export const ddsFontHeadingMediumParagraphSpacing = "0.4em";
export const ddsFontHeadingMediumParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingSmallLetterSpacing = "0em";
export const ddsFontHeadingSmallParagraphSpacing = "0.4em";
export const ddsFontHeadingSmallParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingXsmallLetterSpacing = "0.01em";
export const ddsFontHeadingXsmallParagraphSpacing = "0.4em";
export const ddsFontHeadingXsmallParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingXxsmallLetterSpacing = "0.01em";
export const ddsFontHeadingXxsmallParagraphSpacing = "0.4em";
export const ddsFontHeadingXxsmallParagraphSpacingNumberEm = 0.4;
export const ddsFontBodyLargeLetterSpacing = "0em";
export const ddsFontBodyLargeParagraphSpacing = "1em";
export const ddsFontBodyLargeParagraphSpacingNumberEm = 1;
export const ddsFontBodyMediumLetterSpacing = "0em";
export const ddsFontBodyMediumParagraphSpacing = "1em";
export const ddsFontBodyMediumParagraphSpacingNumberEm = 1;
export const ddsFontBodySmallLetterSpacing = "0.01em";
export const ddsFontBodySmallParagraphSpacing = "1em";
export const ddsFontBodySmallParagraphSpacingNumberEm = 1;
export const ddsFontBodyXsmallLetterSpacing = "0.01em";
export const ddsFontBodyXsmallParagraphSpacing = "1em";
export const ddsFontBodyXsmallParagraphSpacingNumberEm = 1;
export const ddsFontLeadMediumLetterSpacing = "0em";
export const ddsFontLeadMediumParagraphSpacing = "1em";
export const ddsFontLeadMediumParagraphSpacingNumberEm = 1;
export const ddsFontCodeMediumLetterSpacing = "0em";
export const ddsFontCodeMediumParagraphSpacing = "1em";
export const ddsFontCodeMediumParagraphSpacingNumberEm = 1;
export const ddsFontLabelMediumLetterSpacing = "0.01em";
export const ddsFontLabelMediumParagraphSpacing = "1em";
export const ddsFontLabelMediumParagraphSpacingNumberEm = 1;