
// Do not edit directly, this file was auto-generated.

export const ddsFontFamilySans = "'IBM Plex Sans', Arial, sans-serif";
export const ddsFontFamilyMonospace = "'IBM Plex Mono', 'Courier New', monospace"; // For kode
export const ddsFontSizeX5 = "5rem";
export const ddsFontSizeX5NumberRem = 5;
export const ddsFontSizeX4 = "4rem";
export const ddsFontSizeX4NumberRem = 4;
export const ddsFontSizeX3 = "3rem";
export const ddsFontSizeX3NumberRem = 3;
export const ddsFontSizeX25 = "2.5rem";
export const ddsFontSizeX25NumberRem = 2.5;
export const ddsFontSizeX2 = "2rem";
export const ddsFontSizeX2NumberRem = 2;
export const ddsFontSizeX15 = "1.5rem";
export const ddsFontSizeX15NumberRem = 1.5;
export const ddsFontSizeX125 = "1.25rem";
export const ddsFontSizeX125NumberRem = 1.25;
export const ddsFontSizeX1125 = "1.125rem";
export const ddsFontSizeX1125NumberRem = 1.125;
export const ddsFontSizeX1 = "1rem";
export const ddsFontSizeX1NumberRem = 1;
export const ddsFontSizeX0875 = "0.875rem";
export const ddsFontSizeX0875NumberRem = 0.875;
export const ddsFontSizeX075 = "0.75rem";
export const ddsFontSizeX075NumberRem = 0.75;
export const ddsFontWeightLight = "300";
export const ddsFontWeightNormal = "400";
export const ddsFontWeightSemiBold = "500";
export const ddsFontWeightBold = "600";
export const ddsFontLineheightX1 = 1.5; // Brukes på mengetekst og artikler
export const ddsFontLineheightX3 = 1.2;
export const ddsFontLineheightX2 = 1.3; // Brukes i komponenter og overskrifter
export const ddsFontLineheightList = 2; // Brukes på lister
export const ddsFontLetterSpacingTight = "-0.01em"; // Brukes på str ×2.5 og større
export const ddsFontLetterSpacingNormal = "0em"; // Brukes på str ×1 og opp til og med ×2
export const ddsFontLetterSpacingLoose = "0.01em"; // Brukes på størrelser under ×1
export const ddsFontParagraphSpacingSmall = "1em";
export const ddsFontParagraphSpacingSmallNumberEm = 1; // Brukes på str ×1_25 og mindre 
export const ddsFontParagraphSpacingMedium = "0.66em";
export const ddsFontParagraphSpacingMediumNumberEm = 0.66; // Brukes på str x1.5, ×2 og ×3 
export const ddsFontParagraphSpacingLarge = "0.5em";
export const ddsFontParagraphSpacingLargeNumberEm = 0.5; // Brukes på str ×3 og større
export const ddsFontParagraphSpacingHeading = "0.4em";
export const ddsFontParagraphSpacingHeadingNumberEm = 0.4; // Brukes på på alle headere (bottom)
export const ddsFontStyleUnderline = "underline";
export const ddsFontStyleNormal = "none";
export const ddsFontStyleItalic = "italic";
export const ddsSpacingPaddingTopHeading = "0.7em";
export const ddsSpacingPaddingTopHeadingNumberEm = 0.7; // Ekstra spacing over dds-header. 70% av størrelsen på headeren
export const ddsSpacingX0 = "0rem";
export const ddsSpacingX0NumberRem = 0;
export const ddsSpacingX0125 = "0.125rem";
export const ddsSpacingX0125NumberRem = 0.125;
export const ddsSpacingX025 = "0.25rem";
export const ddsSpacingX025NumberRem = 0.25;
export const ddsSpacingX05 = "0.5rem";
export const ddsSpacingX05NumberRem = 0.5;
export const ddsSpacingX075 = "0.75rem";
export const ddsSpacingX075NumberRem = 0.75;
export const ddsSpacingX1 = "1rem";
export const ddsSpacingX1NumberRem = 1;
export const ddsSpacingX15 = "1.5rem";
export const ddsSpacingX15NumberRem = 1.5;
export const ddsSpacingX2 = "2rem";
export const ddsSpacingX2NumberRem = 2;
export const ddsSpacingX25 = "2.5rem";
export const ddsSpacingX25NumberRem = 2.5;
export const ddsSpacingX3 = "3rem";
export const ddsSpacingX3NumberRem = 3;
export const ddsSpacingX4 = "4rem";
export const ddsSpacingX4NumberRem = 4;
export const ddsSpacingX6 = "6rem";
export const ddsSpacingX6NumberRem = 6;
export const ddsSpacingX10 = "10rem";
export const ddsSpacingX10NumberRem = 10;
export const ddsGridXsGutterSize = "16px";
export const ddsGridXsGutterSizeNumberPx = 16;
export const ddsGridXsCount = "4";
export const ddsGridSmGutterSize = "16px";
export const ddsGridSmGutterSizeNumberPx = 16;
export const ddsGridSmCount = "8";
export const ddsGridLgGutterSize = "24px";
export const ddsGridLgGutterSizeNumberPx = 24;
export const ddsGridLgCount = "12";
export const ddsGridMdGutterSize = "24px";
export const ddsGridMdGutterSizeNumberPx = 24;
export const ddsGridMdCount = "12";
export const ddsGridXlGutterSize = "24px";
export const ddsGridXlGutterSizeNumberPx = 24;
export const ddsGridXlCount = "12";
export const ddsSizeIconLarge = "40px";
export const ddsSizeIconLargeNumberPx = 40;
export const ddsSizeIconMedium = "24px";
export const ddsSizeIconMediumNumberPx = 24;
export const ddsSizeIconSmall = "16px";
export const ddsSizeIconSmallNumberPx = 16;
export const ddsSizeIconComponent = "1.3em";
export const ddsSizeIconComponentNumberEm = 1.3; // Brukes i komponenter. Relativ til tekststørrelsen
export const ddsBreakpointXs = "1px";
export const ddsBreakpointXsNumberPx = 1;
export const ddsBreakpointSm = "600px";
export const ddsBreakpointSmNumberPx = 600;
export const ddsBreakpointMd = "960px";
export const ddsBreakpointMdNumberPx = 960;
export const ddsBreakpointLg = "1280px";
export const ddsBreakpointLgNumberPx = 1280;
export const ddsBreakpointXl = "1920px";
export const ddsBreakpointXlNumberPx = 1920;
export const ddsZindexSkiptocontent = "250"; // Brukes for dds-skiptocontent
export const ddsZindexModalBackdrop = "200"; // Brukes for dds-modal
export const ddsZindexDrawer = "180"; // Brukes for dds-drawer
export const ddsZindexDrawerBackdrop = "180"; // Brukes for dds-drawer
export const ddsZindexOverflowmenu = "160"; // Brukes for dds-overflowmenu
export const ddsZindexPopover = "140"; // Brukes for dds-popover og kalender i datepicker
export const ddsZindexTooltip = "120"; // Brukes for dds-tooltip
export const ddsZindexDropdown = "100"; // Dropdown brukes for bl.a søkeforslag, dropdown i select
export const ddsZindexSticky = "50"; // Sticky header skal dekke til flat innhold i gruppen (tabell o.l.). Den skal legge seg under elementer som stiller med egne flater
export const ddsZindexAbsoluteElement = "1"; // Dekorative elementer med absolutt posisjon, som ellers hadde blitt skjult bak forelder
export const ddsColorData10Default = "#62abcb";
export const ddsColorData10Subtle = "#135774";
export const ddsColorData10Border = "#62abcb";
export const ddsColorDataRed100 = "#f8d2d4";
export const ddsColorDataRed200 = "#f0a5a9";
export const ddsColorDataRed300 = "#f4858b";
export const ddsColorDataRed400 = "#e14b53";
export const ddsColorDataRed500 = "#da1e28";
export const ddsColorDataRed600 = "#ae1820";
export const ddsColorDataRed700 = "#831218";
export const ddsColorDataRed800 = "#570c10";
export const ddsColorDataRed900 = "#2c0608";
export const ddsColorDataMagenta100 = "#f7d9f2";
export const ddsColorDataMagenta200 = "#edb5e4";
export const ddsColorDataMagenta300 = "#e079d0";
export const ddsColorDataMagenta400 = "#d54dc0";
export const ddsColorDataMagenta500 = "#cb20b0";
export const ddsColorDataMagenta600 = "#a21a8d";
export const ddsColorDataMagenta700 = "#7a136a";
export const ddsColorDataMagenta800 = "#510d46";
export const ddsColorDataMagenta900 = "#290623";
export const ddsColorDataBrown100 = "#f0ddd5";
export const ddsColorDataBrown200 = "#e1bcac";
export const ddsColorDataBrown300 = "#d19a82";
export const ddsColorDataBrown400 = "#c27959";
export const ddsColorDataBrown500 = "#b3572f";
export const ddsColorDataBrown600 = "#8f4626";
export const ddsColorDataBrown700 = "#6b341c";
export const ddsColorDataBrown800 = "#482313";
export const ddsColorDataBrown900 = "#241109";
export const ddsColorDataOlive100 = "#e9e7cd";
export const ddsColorDataOlive200 = "#cdc9a1";
export const ddsColorDataOlive300 = "#b3ae71";
export const ddsColorDataOlive400 = "#989344";
export const ddsColorDataOlive500 = "#7c7518";
export const ddsColorDataOlive600 = "#635e13";
export const ddsColorDataOlive700 = "#4a460e";
export const ddsColorDataOlive800 = "#322f0a";
export const ddsColorDataOlive900 = "#191705";
export const ddsColorDataGreen100 = "#d7e8cf";
export const ddsColorDataGreen200 = "#aed19e";
export const ddsColorDataGreen300 = "#95c280";
export const ddsColorDataGreen400 = "#619947";
export const ddsColorDataGreen500 = "#3a8019";
export const ddsColorDataGreen600 = "#2e6614";
export const ddsColorDataGreen700 = "#234d0f";
export const ddsColorDataGreen800 = "#17330a";
export const ddsColorDataGreen900 = "#0c1a05";
export const ddsColorDataTeal100 = "#c2e2e1";
export const ddsColorDataTeal200 = "#90ccc9";
export const ddsColorDataTeal300 = "#5dafad";
export const ddsColorDataTeal400 = "#2c9390";
export const ddsColorDataTeal500 = "#007d79";
export const ddsColorDataTeal600 = "#006461";
export const ddsColorDataTeal700 = "#004b49";
export const ddsColorDataTeal800 = "#003230";
export const ddsColorDataTeal900 = "#001918";
export const ddsColorDataDeepblue100 = "#c6e3f1";
export const ddsColorDataDeepblue200 = "#93cee6";
export const ddsColorDataDeepblue300 = "#62abcb";
export const ddsColorDataDeepblue400 = "#358fb5";
export const ddsColorDataDeepblue500 = "#196b8f";
export const ddsColorDataDeepblue600 = "#135774";
export const ddsColorDataDeepblue700 = "#0e455e";
export const ddsColorDataDeepblue800 = "#0d3445";
export const ddsColorDataDeepblue900 = "#05151d";
export const ddsColorDataBlue100 = "#cfe0ff";
export const ddsColorDataBlue200 = "#9fc0ff";
export const ddsColorDataBlue300 = "#6fa1fe";
export const ddsColorDataBlue400 = "#3f81fe";
export const ddsColorDataBlue500 = "#0f62fe";
export const ddsColorDataBlue600 = "#0c4ecb";
export const ddsColorDataBlue700 = "#093b98";
export const ddsColorDataBlue800 = "#062766";
export const ddsColorDataBlue900 = "#031433";
export const ddsColorDataPurple100 = "#e8d9fe";
export const ddsColorDataPurple200 = "#d0b2fe";
export const ddsColorDataPurple300 = "#b98cfd";
export const ddsColorDataPurple400 = "#a165fd";
export const ddsColorDataPurple500 = "#8a3ffc";
export const ddsColorDataPurple600 = "#6e32ca";
export const ddsColorDataPurple700 = "#532697";
export const ddsColorDataPurple800 = "#371965";
export const ddsColorDataPurple900 = "#1c0d32";
export const ddsColorDataGray100 = "#e3e3e3";
export const ddsColorDataGray200 = "#c7c7c7";
export const ddsColorDataGray300 = "#aaaaaa";
export const ddsColorDataGray400 = "#8e8e8e";
export const ddsColorDataGray500 = "#727272";
export const ddsColorDataGray600 = "#5b5b5b";
export const ddsColorDataGray700 = "#444444";
export const ddsColorDataGray800 = "#2e2e2e";
export const ddsColorDataGray900 = "#171717";
export const ddsColorData01Default = "#6fa1fe";
export const ddsColorData01Subtle = "#0c4ecb";
export const ddsColorData01Border = "#6fa1fe";
export const ddsColorData02Default = "#d19a82";
export const ddsColorData02Subtle = "#8f4626";
export const ddsColorData02Border = "#d19a82";
export const ddsColorData03Default = "#aaaaaa";
export const ddsColorData03Subtle = "#5b5b5b";
export const ddsColorData03Border = "#aaaaaa";
export const ddsColorData04Default = "#95c280";
export const ddsColorData04Subtle = "#2e6614";
export const ddsColorData04Border = "#95c280";
export const ddsColorData05Default = "#b98cfd";
export const ddsColorData05Subtle = "#6e32ca";
export const ddsColorData05Border = "#b98cfd";
export const ddsColorData06Default = "#e079d0";
export const ddsColorData06Subtle = "#a21a8d";
export const ddsColorData06Border = "#e079d0";
export const ddsColorData07Default = "#b3ae71";
export const ddsColorData07Subtle = "#635e13";
export const ddsColorData07Border = "#b3ae71";
export const ddsColorData08Default = "#f4858b";
export const ddsColorData08Subtle = "#ae1820";
export const ddsColorData08Border = "#f4858b";
export const ddsColorData09Default = "#5dafad";
export const ddsColorData09Subtle = "#006461";
export const ddsColorData09Border = "#5dafad";
export const ddsColorBgDefault = "#181a1c"; // UI shell base color
export const ddsColorBgSubtle = "#22272a"; // Alternative UI shell base color
export const ddsColorSurfaceDefault = "#181a1c"; // Default bg
export const ddsColorSurfaceSubtle = "#22272a"; // Subtle surface color
export const ddsColorSurfaceMedium = "#303438"; // Medium surface color
export const ddsColorSurfaceHoverDefault = "#062c45"; // Hover on surface (default, subtle, medium)
export const ddsColorSurfaceHoverSubtle = "#22272a"; // Subtle hover on surface (default, medium)
export const ddsColorSurfaceSelectedDefault = "#062c45"; // Selected state for surface (default, subtle, medium)
export const ddsColorSurfaceInverseDefault = "#354754"; // Can be used as a surface for menu, navigation, footer etc
export const ddsColorSurfaceInverseHover = "#2a3943"; // Hover on surface.inverse
export const ddsColorSurfaceInverseSelected = "#202b32"; // selected on surface.inverse
export const ddsColorSurfaceActionResting = "#589ac6"; // Primary button bg
export const ddsColorSurfaceActionHover = "#9fc5de"; // Hover on surface.action/selected
export const ddsColorSurfaceActionSelected = "#589ac6"; // Selected state for components such as togglebutton, togglebar, progress tracker, checkbox etc
export const ddsColorSurfaceActionDangerResting = "#e47373"; // Danger button
export const ddsColorSurfaceActionDangerHover = "#efafaf"; // Hover on surface.action-danger
export const ddsColorSurfaceActionSelectedDisabled = "#77838c"; // bg on a selected disabled checkbox, radio etc
export const ddsColorSurfaceDangerDefault = "#561616"; // tag, message, errormessage
export const ddsColorSurfaceDangerStrong = "#dc4b4b"; // tag strong value
export const ddsColorSurfaceSuccessDefault = "#284c29"; // tag, message
export const ddsColorSurfaceSuccessStrong = "#65be66"; // tag with strong value
export const ddsColorSurfaceWarningDefault = "#494317"; // tag, message
export const ddsColorSurfaceWarningStrong = "#f4e04d"; // tag strong value
export const ddsColorSurfaceInfoDefault = "#2a4b61"; // tag, message
export const ddsColorSurfaceInfoStrong = "#75b9e6"; // tag strong value
export const ddsColorSurfacePaperDefault = "#303438"; // modal, drawer, popover etc
export const ddsColorSurfaceBackdropDefault = "#0b0d0e80"; // background overlay for modals (50%)
export const ddsColorSurfaceFieldDefault = "#0b0d0e"; // Form elements (textinput, datepicker etc)
export const ddsColorSurfaceFieldDisabled = "#303438"; // disabled state on surface.field
export const ddsColorSurfaceHighlightedDefault = "#833a21"; // bg for highlighted text on text.default. Use with $Text
export const ddsColorSurfaceScrollbar = "#545c62"; // Used for scrollbar
export const ddsColorSurfaceNotification = "#d83737"; // bg on a notification
export const ddsColorSurfaceSkeleton = "#545c62"; // Used for skeleton
export const ddsColorBorderDefault = "#77838c"; // Form components, togglebutton, secondary button, checkbox etc
export const ddsColorBorderSubtle = "#545c62"; // Dropdown, tooltip, overflow etc
export const ddsColorBorderInverse = "#acbbc6"; // Border or divider on surface.inverse
export const ddsColorBorderActionDefault = "#589ac6"; // Used in progress tracker
export const ddsColorBorderActionHover = "#9fc5de"; // Hover on secondary button etc
export const ddsColorBorderSuccess = "#519852"; // Used with tag-default
export const ddsColorBorderWarning = "#ccba35"; // Tag.default
export const ddsColorBorderDanger = "#ad2c2c"; // Tag.default, error message field
export const ddsColorBorderInfo = "#5197c5"; // Tag.default
export const ddsColorBorderOnAction = "#181a1c"; // Used on primary split button
export const ddsColorTextDefault = "#ffffff"; // default text, heading, body. on surface.hover
export const ddsColorTextMedium = "#e9ebec"; // Label, etc
export const ddsColorTextSubtle = "#d6dadd"; // Disabled or less important text
export const ddsColorTextOnInverse = "#ffffff"; // On surface.inverse
export const ddsColorTextDanger = "#efafaf"; // Error text on paper, or default or subtle surafce/bg
export const ddsColorTextOnAction = "#0b0d0e"; // On surface.action (primary and danger button)
export const ddsColorTextOnStatusDefault = "#ffffff"; // On default status surfaces
export const ddsColorTextOnStatusStrong = "#0b0d0e"; // On status surfaces with strong prop
export const ddsColorTextActionResting = "#9fc5de"; // Link, number in progress tracker
export const ddsColorTextActionHover = "#e7f1f7"; // Hover on text.action
export const ddsColorTextRequiredfield = "#efafaf"; // Asterix to indicate required field
export const ddsColorTextActionVisited = "#cca9e1"; // Used for visited links
export const ddsColorTextActionVisitedOnInverse = "#cca9e1"; // Used for visited links on inverse surfaces
export const ddsColorTextOnNotification = "#ffffff"; // Used on surface.notification
export const ddsColorTextOnPrimaryDefault = "#ffffff"; // Used on brand.primary-default
export const ddsColorTextOnPrimarySubtle = "#ffffff"; // Used on brand.primary-subtle
export const ddsColorTextOnPrimaryMedium = "#ffffff"; // Used on brand.primary-medium
export const ddsColorTextOnPrimaryStrong = "#ffffff"; // Used on brand.primary-strong
export const ddsColorTextOnSecondaryDefault = "#0b0d0e"; // Used on brand.secondary-default
export const ddsColorTextOnSecondarySubtle = "#ffffff"; // Used on brand.secondary-subtle
export const ddsColorTextOnSecondaryMedium = "#ffffff"; // Used on brand.secondary-medium
export const ddsColorTextOnSecondaryStrong = "#0b0d0e"; // Used on brand.secondary-strong
export const ddsColorTextOnTertiaryDefault = "#0b0d0e"; // Used on brand.tertiary-default
export const ddsColorTextOnTertiarySubtle = "#ffffff"; // Used on brand.tertiary-subtle
export const ddsColorTextOnTertiaryMedium = "#0b0d0e"; // Used on brand.tertiary-medium
export const ddsColorTextOnTertiaryStrong = "#0b0d0e"; // Used on brand.tertiary-strong
export const ddsColorTextOnDataDefault = "#0b0d0e"; // Used on data. with default value
export const ddsColorTextOnDataSubtle = "#ffffff"; // Used on data. with subtle value
export const ddsColorIconDefault = "#ffffff"; // Often used with text.default
export const ddsColorIconMedium = "#e9ebec"; // Often used with text.medium
export const ddsColorIconSubtle = "#d6dadd"; // Often used with text.subtle
export const ddsColorIconOnInverse = "#ffffff"; // On surface.inverse
export const ddsColorIconOnAction = "#0b0d0e"; // On surface.action (primary and danger button)
export const ddsColorIconActionResting = "#9fc5de"; // Often used with Text.action
export const ddsColorIconActionHover = "#e7f1f7"; // hover on icon-action
export const ddsColorIconOnSuccessDefault = "#c1e5c2"; // On surface.success-default
export const ddsColorIconOnSuccessStrong = "#0b0d0e"; // On surface-success-strong
export const ddsColorIconOnWarningDefault = "#fbf3b8"; // On surface.warning-default
export const ddsColorIconOnWarningStrong = "#0b0d0e"; // On surface.warning-strong
export const ddsColorIconOnDangerDefault = "#efafaf"; // On surface.danger-default
export const ddsColorIconOnDangerStrong = "#0b0d0e"; // On surface.danger-strong
export const ddsColorIconOnInfoDefault = "#c8e3f5"; // On surface.info-default
export const ddsColorIconOnInfoStrong = "#0b0d0e"; // On surface.info-strong
export const ddsColorIconDanger = "#efafaf"; // Error icon on paper, or default or subtle surafce/bg
export const ddsColorBrandPrimaryDefault = "#354754"; // Primary brand color
export const ddsColorBrandPrimarySubtle = "#2a3943"; // Primary brand color
export const ddsColorBrandPrimaryMedium = "#405767"; // Primary brand color
export const ddsColorBrandPrimaryStrong = "#4f6a7e"; // Primary brand color
export const ddsColorBrandSecondaryDefault = "#9ab8b7"; // Secondary brand color
export const ddsColorBrandSecondarySubtle = "#2b3a3a"; // Secondary brand color
export const ddsColorBrandSecondaryMedium = "#4d6463"; // Secondary brand color
export const ddsColorBrandSecondaryStrong = "#b8cdcd"; // Secondary brand color
export const ddsColorBrandTertiaryDefault = "#f27e55"; // Tertiary brand color
export const ddsColorBrandTertiarySubtle = "#a24422"; // Tertiary brand color
export const ddsColorBrandTertiaryMedium = "#f2a68f"; // Tertiary brand color
export const ddsColorBrandTertiaryStrong = "#ffd6ca"; // Tertiary brand color
export const ddsColorFocusOutside = "#f1f8fd"; // Contrast to .inside
export const ddsColorFocusInside = "#2a4b61"; // Contrast to .outside
export const ddsShadowLarge = "8px 16px 32px 0px rgba(11, 13, 14, 80%)"; // Dialoger. Eksempel: modal, drawer, popover
export const ddsShadowMedium = "2px 4px 8px 0px rgba(11, 13, 14, 80%)"; // Dropdowns. Eksempel: overflowmenu, dropdown
export const ddsShadowSmall = "1px 2px 4px 0px rgba(11, 13, 14, 80%)"; // Eksempel: tooltip
export const ddsBorderRadiusButton = "2px";
export const ddsBorderRadiusButtonNumberPx = 2; // For use in button component and togglebutton
export const ddsBorderRadiusSurface = "4px";
export const ddsBorderRadiusSurfaceNumberPx = 4; // Most surfaces, for example cards, papers, messages, backgrounds in GUI
export const ddsBorderRadiusInput = "2px";
export const ddsBorderRadiusInputNumberPx = 2; // All input fields, and check boxes
export const ddsBorderRadiusChip = "4px";
export const ddsBorderRadiusChipNumberPx = 4; // Chips and tags
export const ddsBorderRadiusRounded = "9999px";
export const ddsBorderRadiusRoundedNumberPx = 9999; // Rounded and circular components such as radiobutton, toggle, togglebutton and progress tracker
export const ddsFontLabelMedium = "600 0.875rem/1.3 'IBM Plex Sans', Arial, sans-serif"; // Label for form components
export const ddsFontBodyLongXsmall = "400 0.75rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Xsmall body text for editorial content
export const ddsFontBodyLongSmall = "400 0.875rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Small body text for editorial content
export const ddsFontBodyLongMedium = "400 1rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Default body text for editorial content
export const ddsFontBodyLongLarge = "400 1.125rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Large body text for editorial content
export const ddsFontHeadingXxsmall = "600 0.75rem/1.3 'IBM Plex Sans', Arial, sans-serif"; // Default h6
export const ddsFontHeadingXsmall = "600 0.875rem/1.3 'IBM Plex Sans', Arial, sans-serif"; // Default h5
export const ddsFontHeadingSmall = "600 1rem/1.3 'IBM Plex Sans', Arial, sans-serif"; // Default h4
export const ddsFontHeadingMedium = "600 1.125rem/1.3 'IBM Plex Sans', Arial, sans-serif"; // Default h3
export const ddsFontHeadingLarge = "400 clamp(1.25rem, 0.833rem + 1.111vw, 1.5rem)/1.3 'IBM Plex Sans', Arial, sans-serif"; // Default h2
export const ddsFontHeadingXlarge = "400 clamp(1.5rem, 0.667rem + 2.222vw, 2rem)/1.3 'IBM Plex Sans', Arial, sans-serif"; // Default H1
export const ddsFontHeadingXxlarge = "300 clamp(2.5rem, 1.667rem + 2.222vw, 3rem)/1.3 'IBM Plex Sans', Arial, sans-serif"; // Display or extra large page title (h1)
export const ddsFontLeadMedium = "300 1.125rem/1.5 'IBM Plex Sans', Arial, sans-serif"; // Lead brukes som ingress når man skriver artikler etc
export const ddsFontCodeMedium = "400 1rem/1.5 'IBM Plex Mono', 'Courier New', monospace"; // Brukes for kodesnutter etc
export const ddsFontBodyShortXsmall = "400 0.75rem/1.3 'IBM Plex Sans', Arial, sans-serif"; //  used with xsmall button and input fields
export const ddsFontBodyShortSmall = "400 0.875rem/1.3 'IBM Plex Sans', Arial, sans-serif"; //  used with small button and input fields
export const ddsFontBodyShortMedium = "400 1rem/1.3 'IBM Plex Sans', Arial, sans-serif"; // Used with medium button and input fields
export const ddsFontBodyShortLarge = "400 1.125rem/1.3 'IBM Plex Sans', Arial, sans-serif"; // Used for large button and large search
export const ddsFontHeadingXxlargeLetterSpacing = "-0.01em";
export const ddsFontHeadingXxlargeParagraphSpacing = "0.4em";
export const ddsFontHeadingXxlargeParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingXlargeLetterSpacing = "0em";
export const ddsFontHeadingXlargeParagraphSpacing = "0.4em";
export const ddsFontHeadingXlargeParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingLargeLetterSpacing = "0em";
export const ddsFontHeadingLargeParagraphSpacing = "0.4em";
export const ddsFontHeadingLargeParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingMediumLetterSpacing = "0em";
export const ddsFontHeadingMediumParagraphSpacing = "0.4em";
export const ddsFontHeadingMediumParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingSmallLetterSpacing = "0em";
export const ddsFontHeadingSmallParagraphSpacing = "0.4em";
export const ddsFontHeadingSmallParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingXsmallLetterSpacing = "0.01em";
export const ddsFontHeadingXsmallParagraphSpacing = "0.4em";
export const ddsFontHeadingXsmallParagraphSpacingNumberEm = 0.4;
export const ddsFontHeadingXxsmallLetterSpacing = "0.01em";
export const ddsFontHeadingXxsmallParagraphSpacing = "0.4em";
export const ddsFontHeadingXxsmallParagraphSpacingNumberEm = 0.4;
export const ddsFontBodyLongLargeLetterSpacing = "0em";
export const ddsFontBodyLongLargeParagraphSpacing = "1em";
export const ddsFontBodyLongLargeParagraphSpacingNumberEm = 1;
export const ddsFontBodyLongMediumLetterSpacing = "0em";
export const ddsFontBodyLongMediumParagraphSpacing = "1em";
export const ddsFontBodyLongMediumParagraphSpacingNumberEm = 1;
export const ddsFontBodyLongSmallLetterSpacing = "0.01em";
export const ddsFontBodyLongSmallParagraphSpacing = "1em";
export const ddsFontBodyLongSmallParagraphSpacingNumberEm = 1;
export const ddsFontBodyLongXsmallLetterSpacing = "0.01em";
export const ddsFontBodyLongXsmallParagraphSpacing = "1em";
export const ddsFontBodyLongXsmallParagraphSpacingNumberEm = 1;
export const ddsFontLeadMediumLetterSpacing = "0em";
export const ddsFontLeadMediumParagraphSpacing = "1em";
export const ddsFontLeadMediumParagraphSpacingNumberEm = 1;
export const ddsFontCodeMediumLetterSpacing = "0em";
export const ddsFontCodeMediumParagraphSpacing = "1em";
export const ddsFontCodeMediumParagraphSpacingNumberEm = 1;
export const ddsFontLabelMediumLetterSpacing = "0.01em";
export const ddsFontLabelMediumParagraphSpacing = "1em";
export const ddsFontLabelMediumParagraphSpacingNumberEm = 1;
export const ddsFontBodyShortLargeLetterSpacing = "0em";
export const ddsFontBodyShortLargeParagraphSpacing = "1em";
export const ddsFontBodyShortLargeParagraphSpacingNumberEm = 1;
export const ddsFontBodyShortMediumLetterSpacing = "0em";
export const ddsFontBodyShortMediumParagraphSpacing = "1em";
export const ddsFontBodyShortMediumParagraphSpacingNumberEm = 1;
export const ddsFontBodyShortSmallLetterSpacing = "0.01em";
export const ddsFontBodyShortSmallParagraphSpacing = "1em";
export const ddsFontBodyShortSmallParagraphSpacingNumberEm = 1;
export const ddsFontBodyShortXsmallLetterSpacing = "0.01em";
export const ddsFontBodyShortXsmallParagraphSpacing = "1em";
export const ddsFontBodyShortXsmallParagraphSpacingNumberEm = 1;