name: 'Chromatic'

on:
  push:
    paths-ignore:
      - '.prettierrc'
      - 'eslint.config.mjs'
      - 'turbo.json'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.md'
      - '**/*.mdx'
      - '**/vitest.config.ts'
      - '**/*.spec.tsx'
      - '.github/**'
      - '.changeset/**'
      - 'packages/dds-formatting/**'
      - 'packages/storybook-components/**'

jobs:
  chromatic:
    if: github.actor != 'dependabot[bot]'
    name: Run Chromatic
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
