name: Design system ci
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clean install
        working-directory: ${{ env.working-directory }}
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        working-directory: ${{ env.working-directory }}
        run: npm run -w @norges-domstoler/dds-components build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify
        working-directory: ${{ env.working-directory }}
        run: npm run -w @norges-domstoler/dds-components verify
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
