name: Deploy Storybook
on:
  push:
    branches: [main]
jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build 🔧
        run: pnpm build:storybook

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: "./storybook-static"

      - name: Deploy 🚀
        uses: actions/deploy-pages@v5
