name: Update browserlist-db

on:
  schedule:
    - cron: '0 0 1 */1 *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/composite-actions/install

      - name: Update browserslist-db
        shell: bash
        run: pnpm dlx update-browserslist-db latest

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: 'chore: oppdaterer browserslist-db'
          branch: 'chore/browserslist-db'
          title: 'chore: oppdaterer browserslist-db'
          body: 'Denne PR-en oppdaterer browserslist-db til siste versjon.'
